title: Daniel Karoly # your name (or website title) here
logo: "/images/dk_crop.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data scientist and chemist with a passion for unlocking insights from data. 
  With a strong foundation in analytical skills and scientific research, I am eager 
  to transition into the data field. I am actively seeking entry-level positions or 
  internships where I can apply my expertise and continue to grow professionally. 
  Let's connect and explore how I can contribute to your team! 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/dkaroly90//">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
